### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by LoveThisWorld002** [LoveThisWorld002/repo#1]
Hi @trueimmortal could you please send me exhentai/ehentai telegram bot if it is not private please?

Also curious about your username why did you choose it anything special?

**Comment by trueimmortal** [comment]
It's on my repo. Good luck setting this overly complicated monstrosity.  The name is something i something i have been using for a while. Nothing special

**Comment by LoveThisWorld002** [comment]
> It's on my repo. Good luck setting this overly complicated monstrosity. The name is something i something i have been using for a while. Nothing special

Thank you very much for your kind answer sir.
